variables:
#  CI_DEBUG_TRACE: "true"
  DEPLOY_PATH: ""

stages:
  - build
  - deploy

build:
  stage: build
  only:
    refs:
    - develop
    - tags
  script:
    - npm install --progress=false --registry=https://mirrors.huaweicloud.com/repository/npm/
    - npm run build
    - ls -al
  artifacts:
    expire_in: 1 week
    paths:
      - dist
  tags:
    - deploy



deploy_test:
  tags:
    - deploy
  stage: deploy
  dependencies:
    - build
  script:
    - cd ~/ansible && git pull
    - ansible deploy_test -m synchronize -a "src=${CI_PROJECT_DIR}/dist/ dest=${DEPLOY_PATH}/dist/ checksum=yes archive=no recursive=yes perms=no delete=yes owner=no group=no rsync_opts='--exclude=.git/'"
    - ansible deploy_test -m file -a "path=${DEPLOY_PATH} owner=www group=www recurse=yes"
  environment:
    name: test
  allow_failure: false
  #when: manual
  only:
    - develop

deploy_prod:
  tags:
    - deploy
  stage: deploy
  dependencies:
    - build
  script:
    - cd ~/ansible && git pull
    - ansible deploy_prod -m synchronize -a "src=${CI_PROJECT_DIR}/dist/ dest=${DEPLOY_PATH}/dist/ checksum=yes archive=no recursive=yes perms=no delete=yes owner=no group=no rsync_opts='--exclude=.git/'"
    - ansible deploy_prod -m file -a "path=${DEPLOY_PATH} owner=www group=www recurse=yes"
  environment:
    name: prod
  allow_failure: false
  when: manual
  only:
    - tags
